### ISSUE TITLE
Translating to mongodb query

### ISSUE THREAD

**Issue by amit777** [rtucek/vue-query-builder#19]
This looks really neat.

Apologies for my ignorance here, but how does one actually use the generated "query"? I would love to generate mongodb queries from this.   I see that https://querybuilder.js.org/ has a plugin to do this for mongodb.  Does your package have a similar methodolgy?

**Comment by rtucek** [comment]
Thank you for your feedback.

Translating the query is consciously not part of the library for 2 reasons:

- It's a frontend library. From that perspective, you usually don't want to craft a raw query in the browser and send it directly to the underlying persistence layer. This is more a job for your backend to interpret the query request and translate it accordingly.
- Currently, the library is un-opinionated in regards to the underlying persistence layer and how you define your rules and groups. So if you query against MongoDB or Elastic Search, the library would need to know where in the document the (likely deep-nested) fields you're looking for are located. Similar, if you query against a SQL database, the library would need to have knowledge about the data model so it knows which tables and JOIN types are required.

However, I'd love to see someone writing plugins for backend like https://querybuilder.js.org/#backends has. I'd definitely reference them.
