### ISSUE TITLE
Rule operators not supported

### ISSUE THREAD

**Issue by chrisborecki** [rtucek/vue-query-builder#25]
Hi, 

are rule operators not supported? 
For example, for constructing a query: "numA > 3"

Note - these are not the And/Or group operators.

**Comment by rtucek** [comment]
The QueryBuilder doesn't come with any pre-defined/opinionated rules out of the box.
Instead, you're supposed to write and inject your own rules - so it should cover your need for numeric comparison.

Please have a look at the [docs for rule configuration](https://rtucek.github.io/vue-query-builder/configuration.html#rules) as well as the corresponding sample on [Code Sandbox](https://codesandbox.io/s/config-rules-cyll8?from-embed). The sample in Code Sandbox shows multiple alternative ways to inject rules as custom components.

**Comment by mlaw93** [comment]
Can you please elaborate on your explanation regarding how one might go about doing as Chris asked?  The docs for rules configuration and the corresponding sample do not clearly explain how one might create a component that will allow for the alternative caparison values 

For example:  'equal','not equal','in','not in','is null','is not null','less','less or equal','greater','greater or equal','between','not between','contains','begins with','ends with'

**Comment by rtucek** [comment]
@mlaw93 & @chrisborecki, please see this sample on code sandbox.
I hope this is what you're looking for.

[![Edit Slot: Rule (advanced)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/slot-rule-advanced-01o6l?fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.vue&theme=dark)

**Comment by jcunhafonte** [comment]
@rtucek Thank you for the answers but I believe this is still unclear. 

In your example, you filter by the type of the field.
How do you achieve something similar to the screenshot?
<img width="672" alt="Screenshot 2020-10-06 at 18 19 10" src="https://user-images.githubusercontent.com/17337794/95237815-96535d00-0800-11eb-9998-751010c8b8a6.png">

Thank you.

**Comment by rtucek** [comment]
This should do the trick
[![Edit Vegetable](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vegetable-iot20?fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.vue&theme=dark)

**Comment by jcunhafonte** [comment]
Thank you @rtucek.
