### ISSUE TITLE
Custom labels

### ISSUE THREAD

**Issue by EvgeniyTaburyanskiy** [rtucek/vue-query-builder#30]
Thanks for component!
Please add custom lables and maxDepth in component params.

**Comment by rtucek** [comment]
Hi, thank you for your feedback.

I understand what you mean by maxDepth, but what do you mean by custom labels exactly? Do you have something in mind that can already be achieved with [custom slots](https://rtucek.github.io/vue-query-builder/styling.html)?

**Comment by rtucek** [comment]
Closed due to inactivity.

**Comment by smithtonson** [comment]
Unless I'm mistaken, the RuleSlotProps being passed into a custom rule-slot don't include the rule definition so you can't customize the label. To do that, the slot would require *at least* the rule identifier to look it up in the query config object.

**Comment by rtucek** [comment]
Kinda... The `RuleSlotProps.ruleComponent` is passed on which gives the component, supposed to be used, as either string or Vue object. Theoretically, that should be sufficient for mapping it with your own label name.

If not, we could add the definition [here](https://github.com/rtucek/vue-query-builder/blob/fd48c101f9ebfea186e19df38f7f41b4f48893fa/src/QueryBuilderRule.vue#L42) as we have it already at hand above at line 18 - feel free to open a PR :wink:

**Comment by smithtonson** [comment]
I'll take a look; the use case I ran into was building a query for elasticsearch. We have hundreds of fields across multiple indexes so instead of creating all those components my components are just based on the data type from elastic (keyword, text, boolean, short, etc...)
