### ISSUE TITLE
Will they make a version for vue 3?

### ISSUE THREAD

**Issue by JoniWaibs** [rtucek/vue-query-builder#37]
Hello, will you make an update for the new version of vue?
I'm building a project and can't find any query builder component for vue 3! Does anyone know one?

**Comment by rtucek** [comment]
Generally yes, I'm open for adding support for Vue 3 someday.
However, as long as the Vue ecosystem [isn't officially "stable"](https://github.com/vuejs/vue-next#supporting-libraries) and the https://vuejs.org/ site still points to Vue 2 by default, I don't bother about Vue 3 yet.
