### ISSUE TITLE
Request: Custom Labels

### ISSUE THREAD

**Issue by oliverborner** [rtucek/vue-query-builder#40]
Currently it is not possible to edit the labels of buttons or selectors like in the version from [dabernathy89/vue-query-builder:](https://github.com/dabernathy89/vue-query-builder)
This would be an important feature for supporting other languages.

Example from dabernathy89's query-builder
labels optional Type: Object
Replace the default labels used in the UI. The default values are:

```
{
  "matchType": "Match Type",
  "matchTypes": [
    {"id": "all", "label": "All"},
    {"id": "any", "label": "Any"}
  ],
  "addRule": "Add Rule",
  "removeRule": "&times;",
  "addGroup": "Add Group",
  "removeGroup": "&times;",
  "textInputPlaceholder": "value",
}
```

**Comment by rtucek** [comment]
What you want to achieve can be done by defining a [groupControl slot](https://rtucek.github.io/vue-query-builder/styling.html#groupcontrol-slot).
You can see more slot-override examples in action by looking at the [theming page](https://rtucek.github.io/vue-query-builder/demos.html#theming).

**Comment by oliverborner** [comment]
Thank you very much!
