### ISSUE TITLE
When will Vue 3 support be ready?

### ISSUE THREAD

**Issue by jhgeluk** [rtucek/vue-query-builder#46]
I would like to use this library/component in my Vue 3 application. When will this be ready for Vue 3?

**Comment by rtucek** [comment]
See #41 and #37
I've been playing with Vue 3 a bit, but didn't had time to work on this library.

**Comment by PumpkinVision** [comment]
Thank you for the info.

**Comment by kwesterfeld2** [comment]
Please review PR #93

**Comment by codearachnid** [comment]
.Bump Thank you @kwesterfeld2  for the PR - any progress on getting this merged in for Vue3 support?

**Comment by ZeeshanAli200** [comment]
do we have any alternative of this?
