### ISSUE TITLE
Is it possible to create components with dynamic values?

### ISSUE THREAD

**Issue by dack94** [rtucek/vue-query-builder#47]
I need to add some custom components but with dynamic values (fill a dropdown with values coming from DB)
is it possible?

thanks!

**Comment by rtucek** [comment]
Basically yes, but your component will have to handle this logic of course.
The query builder just expects that the component reports the selected value via v-model API (see [docs](https://rtucek.github.io/vue-query-builder/configuration.html#rules)).

**Comment by dack94** [comment]
This is my situation:
- i've a list of objects (let's call each object 'Survey') and they are shown in a record list (the classic index page)
- In order to create a Survey, the user land on a form when there are multiple questions and for each of them there is an answer
- one field is called 'visible if' and your plugin is linked to this field
- basically the goal is to specify the logic in order to show this line in the record list page (visible if Survey1.Question2 = 3)
- i'm struggling cause it should be dynamic (today i'm using the **Survey** object but tomorrow i'll use the **Exigence Object**)

image that in the form page i import my component **dropdown-custom** and used it in your plugin. How can i tell to the component 'Hey you need to fill yourself with these questions' ?

**Comment by rtucek** [comment]
Your question is not query-builder specific - it requires a bit more sophisticated knowledge about Vue, though :)

This sample may illustrate what you're looking for. It creates "new/dynamic" components, which fetch values from an API and use vue-select for visualization.

[![Edit Dynamic dropdown](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dynamic-dropdown-1c48z?fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.vue&theme=dark)

**Comment by dack94** [comment]
Totally agree with you :) 
Great it does the work!

Thanks for your help!

**Comment by rtucek** [comment]
I guess your question is related to #19, right?

If not, pls open another issue for further discussion :pray:
