### ISSUE TITLE
Can you provide the better way to test a rule ?

### ISSUE THREAD

**Issue by dack94** [rtucek/vue-query-builder#51]
If it's easy for you, can you provide the better way to test a rule ?
i'm struggling a bit with it (in order to pass configuration and model) and maybe you've already done this before.

Thanks!

**Comment by rtucek** [comment]
Not sure what you want to test and how.

Rules are simply "just" components, that you pass on to the query builder and need to adhere to the v-model API. They should be unit tested on their own and independently of their context. All you need to assert is that they adhere to the v-model API as outlined in [the docs](https://rtucek.github.io/vue-query-builder/demos.html#custom-components).

Could you further elaborate on what you're exactly trying to achieve?
